/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.DriverManager;
import net.proteanit.sql.DbUtils;
import javax.swing.JComboBox;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JDateChooserBeanInfo;
import com.toedter.calendar.JDateChooserCellEditor;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;



public class ManageMedicine extends javax.swing.JFrame {
    
     

    /**
     * Creates new form ManageMedicine
     */
    public ManageMedicine() {
        initComponents();
        SelectMed();
        GetCompany();
    }
    
    
 Connection Con=null;
    Statement St=null, St1=null;
    ResultSet Rs=null,RS;
    
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inventoryPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        company_txt = new javax.swing.JComboBox<>();
        restockDate_txt = new javax.swing.JTextField();
        medId_txt = new javax.swing.JTextField();
        batchNo_txt = new javax.swing.JTextField();
        medName_txt = new javax.swing.JTextField();
        mg_txt = new javax.swing.JTextField();
        dosage_txt = new javax.swing.JTextField();
        description_txt = new javax.swing.JTextField();
        expDate_txt = new javax.swing.JTextField();
        quantity_txt = new javax.swing.JTextField();
        ppu_txt = new javax.swing.JTextField();
        updateMedBtn = new javax.swing.JButton();
        addMedBtn = new javax.swing.JButton();
        deleteMedBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageMedTable = new javax.swing.JTable();
        categoryCombo = new javax.swing.JComboBox<>();
        ManageMed_Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryPanel.setBackground(new java.awt.Color(0, 0, 0,0));
        inventoryPanel.setForeground(new java.awt.Color(255, 255, 255));
        inventoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("MEDICINE ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventoryPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 26, 154, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("MEDICINE NAME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventoryPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("CATEGORY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventoryPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 154, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("DOSAGE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventoryPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("DESCRIPTION");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        inventoryPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 183, -1, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("MG");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventoryPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 26, 148, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("COMPANY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventoryPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 160, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("BATCH NO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventoryPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 154, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("QUANTITY");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inventoryPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("PRICE PER UNIT");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inventoryPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 150, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("EXPIRY DATE");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        inventoryPanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 148, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("RESTOCK DATE");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inventoryPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 150, -1));

        company_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        company_txt.setForeground(new java.awt.Color(0, 154, 0));
        company_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                company_txtActionPerformed(evt);
            }
        });
        inventoryPanel.add(company_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 220, 50));

        restockDate_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        restockDate_txt.setForeground(new java.awt.Color(153, 153, 153));
        restockDate_txt.setText("yyyy-mm-dd");
        restockDate_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                restockDate_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                restockDate_txtFocusLost(evt);
            }
        });
        restockDate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restockDate_txtActionPerformed(evt);
            }
        });
        inventoryPanel.add(restockDate_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 260, 220, 50));

        medId_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        medId_txt.setForeground(new java.awt.Color(0, 153, 0));
        medId_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medId_txtActionPerformed(evt);
            }
        });
        inventoryPanel.add(medId_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 220, 50));

        batchNo_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        batchNo_txt.setForeground(new java.awt.Color(0, 153, 0));
        batchNo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNo_txtActionPerformed(evt);
            }
        });
        inventoryPanel.add(batchNo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 220, 50));

        medName_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        medName_txt.setForeground(new java.awt.Color(0, 153, 0));
        inventoryPanel.add(medName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 220, 50));

        mg_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mg_txt.setForeground(new java.awt.Color(0, 154, 0));
        mg_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mg_txtActionPerformed(evt);
            }
        });
        inventoryPanel.add(mg_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 220, 50));

        dosage_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        dosage_txt.setForeground(new java.awt.Color(0, 154, 0));
        dosage_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosage_txtActionPerformed(evt);
            }
        });
        inventoryPanel.add(dosage_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 220, 50));

        description_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        description_txt.setForeground(new java.awt.Color(0, 154, 0));
        inventoryPanel.add(description_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 220, 50));

        expDate_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        expDate_txt.setForeground(new java.awt.Color(153, 153, 153));
        expDate_txt.setText("yyyy/mm/dd");
        expDate_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expDate_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                expDate_txtFocusLost(evt);
            }
        });
        expDate_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expDate_txtKeyTyped(evt);
            }
        });
        inventoryPanel.add(expDate_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 220, 50));

        quantity_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        quantity_txt.setForeground(new java.awt.Color(0, 154, 0));
        inventoryPanel.add(quantity_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 100, 220, 50));

        ppu_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ppu_txt.setForeground(new java.awt.Color(0, 154, 0));
        inventoryPanel.add(ppu_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, 220, 50));

        updateMedBtn.setBackground(new java.awt.Color(0, 153, 0));
        updateMedBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        updateMedBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateMedBtn.setText("UPDATE");
        updateMedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMedBtnMouseClicked(evt);
            }
        });
        updateMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMedBtnActionPerformed(evt);
            }
        });
        inventoryPanel.add(updateMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, 120, 50));

        addMedBtn.setBackground(new java.awt.Color(0, 153, 0));
        addMedBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        addMedBtn.setForeground(new java.awt.Color(255, 255, 255));
        addMedBtn.setText("ADD");
        addMedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMedBtnMouseClicked(evt);
            }
        });
        addMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedBtnActionPerformed(evt);
            }
        });
        inventoryPanel.add(addMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 120, 50));

        deleteMedBtn.setBackground(new java.awt.Color(0, 153, 0));
        deleteMedBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        deleteMedBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteMedBtn.setText("DELETE");
        deleteMedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMedBtnMouseClicked(evt);
            }
        });
        deleteMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMedBtnActionPerformed(evt);
            }
        });
        inventoryPanel.add(deleteMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 120, 50));

        manageMedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Medicine ID", "Batch No", "Medicine Name", "Category", "mg", "Dosage", "Description", "Expiry Date", "Company", "Quantity", "Price Per Unit", "Restock Date"
            }
        ));
        manageMedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageMedTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(manageMedTable);

        inventoryPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 402, 1490, 306));

        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Capsule", "Syrups", "Creams and Ointments", "Suspensions" }));
        inventoryPanel.add(categoryCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 220, 50));

        getContentPane().add(inventoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1530, 730));

        ManageMed_Close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ManageMed_Close.setForeground(new java.awt.Color(204, 0, 51));
        ManageMed_Close.setText("X");
        ManageMed_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageMed_CloseActionPerformed(evt);
            }
        });
        getContentPane().add(ManageMed_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restockDate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restockDate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restockDate_txtActionPerformed

    private void batchNo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNo_txtActionPerformed

    private void company_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_company_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_company_txtActionPerformed

    private void mg_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mg_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mg_txtActionPerformed

    private void dosage_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosage_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosage_txtActionPerformed

    private void addMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedBtnActionPerformed

    private void deleteMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMedBtnActionPerformed

    private void updateMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMedBtnActionPerformed

    private void medId_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medId_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medId_txtActionPerformed

    private void deleteMedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMedBtnMouseClicked
                                        
//    if (medId_txt.getText().isEmpty() || batchNo_txt.getText().isEmpty()) {
//       if (medId_txt.getText().isEmpty() || batchNo_txt.getText().isEmpty()) {
    if (medId_txt.getText().isEmpty() || batchNo_txt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Medicine ID and batch No of the Medicine to be Deleted");
    } else {
        try {
            String M_Id = medId_txt.getText();
            String B_No = batchNo_txt.getText();

            // Update the status to 'INACTIVE' in the backend
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb", "root", "Sql@2003");
            String updateQuery = "UPDATE PRODUCTS SET STATUS = 'INACTIVE' WHERE PRODUCT_ID = ? AND BATCH_NO = ?";
            PreparedStatement updateStmt = con.prepareStatement(updateQuery);
            updateStmt.setString(1, M_Id);
            updateStmt.setString(2, B_No);
            updateStmt.executeUpdate();
            con.close();

            // Remove the selected row from the frontend
            DefaultTableModel model = (DefaultTableModel) manageMedTable.getModel();
            int selectedRowIndex = manageMedTable.getSelectedRow();
            if (selectedRowIndex != -1) {
                model.removeRow(selectedRowIndex);
                JOptionPane.showMessageDialog(this, "Medicine Deleted Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "No row selected for deletion");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }     
    }//GEN-LAST:event_deleteMedBtnMouseClicked

    private void ManageMed_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageMed_CloseActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            Dashboard prevPage = new Dashboard();
            prevPage.setVisible(true);
        }
    }//GEN-LAST:event_ManageMed_CloseActionPerformed

    private int getManufacturerId(String manufacturerName) throws SQLException {
    int manufacturerId = -1; // Initialize to an invalid ID
    
    // Perform a database query to retrieve the ID based on the name
    String query = "SELECT MANUFACTURE_ID FROM MANUFACTURER WHERE M_NAME = ?";
    PreparedStatement statement = Con.prepareStatement(query);
    statement.setString(1, manufacturerName);
    ResultSet resultSet = statement.executeQuery();
    if (resultSet.next()) {
        manufacturerId = resultSet.getInt("MANUFACTURE_ID");
    }
    
    return manufacturerId;
}

    
    private void addMedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMedBtnMouseClicked
                                              
    try {
        // Establish the database connection
        Con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb", "root", "Sql@2003");

        // Retrieve product name from the text field
        String ManName = company_txt.getSelectedItem().toString();



        int ManId = getManufacturerId(ManName);

        // Prepare the INSERT statement
        PreparedStatement add = Con.prepareStatement("INSERT INTO PRODUCTS "
                + "(product_id, batch_no, p_name, description, category, mg, dosage, quantity_available, last_restock_date, expiry_date, price, man_id, status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)");

        // Set parameters for the INSERT statement
        add.setString(1, medId_txt.getText());
        add.setString(2, batchNo_txt.getText());
        add.setString(3, medName_txt.getText()); // Use the retrieved product name
        add.setString(4, description_txt.getText());
        add.setString(5, categoryCombo.getSelectedItem().toString());
        add.setString(6, mg_txt.getText()); // Assuming mg_txt contains dosage as a string
        add.setString(7, dosage_txt.getText());
        add.setString(8, quantity_txt.getText());
        add.setString(9, restockDate_txt.getText());
        add.setString(10, expDate_txt.getText());
        
        add.setString(11, ppu_txt.getText());
        add.setInt(12, ManId); // Set the product ID obtained earlier
        
        int quantityAvailable = Integer.parseInt(quantity_txt.getText());
        String status = (quantityAvailable > 0) ? "ACTIVE" : "INACTIVE";
        
        
        add.setString(13, status);
        // Execute the INSERT statement
        int row = add.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Medicine added Successfully");
        updateStatusIfQuantityZero();
        


        

        // Close the database connection
        Con.close();

        // Refresh the table after adding a new entry
        SelectMed();

    } catch (SQLException e) {
         if (e.getSQLState().equals("45000") && e.getMessage().contains("expiry date")) {
    System.out.println("SQL State: " + e.getSQLState());
    System.out.println("Error Message: " + e.getMessage());
    SwingUtilities.invokeLater(() -> {
        JOptionPane.showMessageDialog(this, "Medicine expired");
    });

        } else {
            e.printStackTrace();
            // You may want to display a generic error message to the user here
        }
    } catch (NumberFormatException e) {
        // Handle parsing errors for dosage
        e.printStackTrace();
        // You may want to display an error message to the user here
    }

    }//GEN-LAST:event_addMedBtnMouseClicked

    private void updateStatusIfQuantityZero() {
    try {
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb", "root", "Sql@2003");
        Statement statement = connection.createStatement();
        
        // Update the status to 'INACTIVE' for products with zero quantity available
        String query = "UPDATE PRODUCTS SET STATUS = 'INACTIVE' WHERE QUANTITY_AVAILABLE = 0";
        int rowsAffected = statement.executeUpdate(query);
        
        System.out.println(rowsAffected + " rows updated.");
        
        connection.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    
    private void expDate_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expDate_txtFocusGained
        // TODO add your handling code here:
       if (expDate_txt.getText().equals("yyyy/mm/dd")) {
        expDate_txt.setText("");
        expDate_txt.setForeground(Color.GREEN); // Set the text color to black
    }
    }//GEN-LAST:event_expDate_txtFocusGained

    private void expDate_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expDate_txtFocusLost
        // TODO add your handling code here:
        if (expDate_txt.getText().isEmpty()) {
        expDate_txt.setText("yyyy/mm/dd");
        expDate_txt.setForeground(new Color(153, 153, 153)); // Set the text color to gray
    }
    }//GEN-LAST:event_expDate_txtFocusLost

    private void expDate_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expDate_txtKeyTyped
    
    }//GEN-LAST:event_expDate_txtKeyTyped

    private void restockDate_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restockDate_txtFocusGained
        // TODO add your handling code here:
            if (restockDate_txt.getText().equals("yyyy-mm-dd")) {
        restockDate_txt.setText("");
        restockDate_txt.setForeground(Color.GREEN); // Set the text color to black
    }
    }//GEN-LAST:event_restockDate_txtFocusGained

    private void restockDate_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_restockDate_txtFocusLost
        // TODO add your handling code here:
         if (restockDate_txt.getText().isEmpty()) {
        restockDate_txt.setText("yyyy-mm-dd");
        restockDate_txt.setForeground(new Color(153, 153, 153)); // Set the text color to gray
    }
    }//GEN-LAST:event_restockDate_txtFocusLost

    private void manageMedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMedTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)manageMedTable.getModel();
       int rowIndex=manageMedTable.getSelectedRow();
       if(rowIndex!=-1){
        medId_txt.setText(model.getValueAt(rowIndex,0).toString());
        batchNo_txt.setText(model.getValueAt(rowIndex,1).toString());
        medName_txt.setText(model.getValueAt(rowIndex,2).toString());
        description_txt.setText(model.getValueAt(rowIndex,3).toString());
        String categoryValue = model.getValueAt(rowIndex, 4).toString(); // Get the value from the table model
        categoryCombo.setSelectedItem(categoryValue); // Set the selected item in the combo box
        mg_txt.setText(model.getValueAt(rowIndex,5).toString());
        dosage_txt.setText(model.getValueAt(rowIndex,6).toString());
        quantity_txt.setText(model.getValueAt(rowIndex,7).toString());
        restockDate_txt.setText(model.getValueAt(rowIndex,8).toString());
        expDate_txt.setText(model.getValueAt(rowIndex,9).toString());
        ppu_txt.setText(model.getValueAt(rowIndex,10).toString());
        String companyValue = model.getValueAt(rowIndex, 11).toString(); // Get the value from the table model
        company_txt.setSelectedItem(companyValue); // Set the selected item in the combo box
//        manId_txt.setEditable(false);
       }
    }//GEN-LAST:event_manageMedTableMouseClicked

    private void updateMedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMedBtnMouseClicked
        // TODO add your handling code here:
        if(medId_txt.getText().isEmpty() || batchNo_txt.getText().isEmpty()||medName_txt.getText().isEmpty()||description_txt.getText().isEmpty()||categoryCombo.getSelectedItem().toString().isEmpty()||
                mg_txt.getText().isEmpty()||dosage_txt.getText().isEmpty()||quantity_txt.getText().isEmpty()||restockDate_txt.getText().isEmpty()||
                expDate_txt.getText().isEmpty()||ppu_txt.getText().isEmpty()||company_txt.getSelectedItem().toString().isEmpty()){
           
            JOptionPane.showMessageDialog(this,"Please fill in all required fields.");
        }
        else{
           try{
             Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb","root","Sql@2003");  
             
             String ManName = company_txt.getSelectedItem().toString();
        int ManId = getManufacturerId(ManName);
             
             PreparedStatement updateStmt = Con.prepareStatement("UPDATE PRODUCTS SET PRODUCT_ID = ?, BATCH_NO = ?, P_NAME = ?, DESCRIPTION = ?, CATEGORY = ?, MG = ?, DOSAGE = ?, QUANTITY_AVAILABLE = ?, LAST_RESTOCK_DATE = ?, EXPIRY_DATE = ?, PRICE = ?, MAN_ID = ?, STATUS = ? WHERE PRODUCT_ID = ? AND BATCH_NO = ? " );
             updateStmt.setString(1, medId_txt.getText());
    updateStmt.setString(2, batchNo_txt.getText());
    updateStmt.setString(3, medName_txt.getText());
    updateStmt.setString(4, description_txt.getText());
    updateStmt.setString(5, categoryCombo.getSelectedItem().toString());
    updateStmt.setString(6,mg_txt.getText());
    updateStmt.setString(7, dosage_txt.getText());
    updateStmt.setString(8,quantity_txt.getText());
    updateStmt.setString(9, restockDate_txt.getText());
    updateStmt.setString(10, expDate_txt.getText());
    updateStmt.setString(11, ppu_txt.getText());
    updateStmt.setInt(12,ManId);
    
    updateStmt.setString(14, medId_txt.getText());
            updateStmt.setString(15, batchNo_txt.getText());
    int quantityAvailable = Integer.parseInt(quantity_txt.getText());
        String status = (quantityAvailable > 0) ? "ACTIVE" : "INACTIVE";
        
        
        updateStmt.setString(13, status);
        
         int rowsAffected = updateStmt.executeUpdate();

    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Medicine Updated Successfully");
        SelectMed();
    } else {
        JOptionPane.showMessageDialog(this, "No rows updated.");
    }
    
             
              SelectMed();
           }catch(SQLException e){
              e.printStackTrace();
           }
          
        }
    }//GEN-LAST:event_updateMedBtnMouseClicked
  
    
 
    
    public void SelectMed(){
    try{
    Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb","root","Sql@2003");
    String query = "SELECT PRODUCT_ID AS 'MEDICINE ID', BATCH_NO, P_NAME AS 'MEDICINE NAME', DESCRIPTION , CATEGORY, MG , DOSAGE, QUANTITY_AVAILABLE , LAST_RESTOCK_DATE , EXPIRY_DATE, PRICE AS 'PRICE PER UNIT', STATUS FROM PRODUCTS WHERE STATUS = 'ACTIVE'";
    St=Con.createStatement();
    Rs=St.executeQuery(query);
    manageMedTable.setModel(DbUtils.resultSetToTableModel(Rs));
    }catch(SQLException e){
        e.printStackTrace();
    }
   
}
    //EXTRACTING M_NAMES FOR DROPDOWN
    public void GetCompany(){
        
        try{
            Con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb","root","Sql@2003");
            St=Con.createStatement();
            String query="SELECT * FROM MANUFACTURER";
            Rs=St.executeQuery(query);
            while(Rs.next()){
                String Mycomp=Rs.getString("M_NAME");
                company_txt.addItem(Mycomp);//Company_txt is name of element(dropdown)
            }
                       
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageMed_Close;
    private javax.swing.JButton addMedBtn;
    private javax.swing.JTextField batchNo_txt;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JComboBox<String> company_txt;
    private javax.swing.JButton deleteMedBtn;
    private javax.swing.JTextField description_txt;
    private javax.swing.JTextField dosage_txt;
    private javax.swing.JTextField expDate_txt;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageMedTable;
    private javax.swing.JTextField medId_txt;
    private javax.swing.JTextField medName_txt;
    private javax.swing.JTextField mg_txt;
    private javax.swing.JTextField ppu_txt;
    private javax.swing.JTextField quantity_txt;
    private javax.swing.JTextField restockDate_txt;
    private javax.swing.JButton updateMedBtn;
    // End of variables declaration//GEN-END:variables
}
