/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ManageCompany extends javax.swing.JFrame {

    /**
     * Creates new form ManageCompany
     */
    public ManageCompany() {
        initComponents();
        SelectMan();
    }
    
   Connection Con=null;
   Statement St=null, St1=null;
   ResultSet Rs=null,RS;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manId_txt = new javax.swing.JTextField();
        manName_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManTable = new javax.swing.JTable();
        addManBtn = new javax.swing.JButton();
        updateManBtn1 = new javax.swing.JButton();
        dltManBtn2 = new javax.swing.JButton();
        ManageMed_Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("MANUFACTURE ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 200, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("MANUFACTURE NAME");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 220, 50));

        manId_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        manId_txt.setForeground(new java.awt.Color(0, 154, 0));
        manId_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manId_txtActionPerformed(evt);
            }
        });
        jPanel2.add(manId_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 280, 50));

        manName_txt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        manName_txt.setForeground(new java.awt.Color(0, 154, 0));
        manName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manName_txtActionPerformed(evt);
            }
        });
        jPanel2.add(manName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 280, 50));

        ManTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ManTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Manufacture Id", "Manufacture Name"
            }
        ));
        ManTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ManTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 540, 480));

        addManBtn.setBackground(new java.awt.Color(0, 153, 0));
        addManBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        addManBtn.setForeground(new java.awt.Color(255, 255, 255));
        addManBtn.setText("ADD");
        addManBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addManBtnMouseClicked(evt);
            }
        });
        addManBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addManBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 120, 50));

        updateManBtn1.setBackground(new java.awt.Color(0, 153, 0));
        updateManBtn1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        updateManBtn1.setForeground(new java.awt.Color(255, 255, 255));
        updateManBtn1.setText("UPDATE");
        updateManBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateManBtn1MouseClicked(evt);
            }
        });
        updateManBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateManBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(updateManBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 120, 50));

        dltManBtn2.setBackground(new java.awt.Color(0, 153, 0));
        dltManBtn2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        dltManBtn2.setForeground(new java.awt.Color(255, 255, 255));
        dltManBtn2.setText("DELETE");
        dltManBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dltManBtn2MouseClicked(evt);
            }
        });
        dltManBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltManBtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(dltManBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 120, 50));

        ManageMed_Close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ManageMed_Close.setForeground(new java.awt.Color(204, 0, 51));
        ManageMed_Close.setText("X");
        ManageMed_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageMed_CloseActionPerformed(evt);
            }
        });
        jPanel2.add(ManageMed_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 0, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -50, 1530, 1190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1550, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manId_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manId_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manId_txtActionPerformed

    private void manName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manName_txtActionPerformed

    private void addManBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addManBtnActionPerformed

    private void updateManBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateManBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateManBtn1ActionPerformed

    private void dltManBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltManBtn2ActionPerformed
        
        if(manId_txt.getText().isEmpty()){
          JOptionPane.showMessageDialog(this,"Enter The Company to be Deleted");
        }
        else{
            try{
               Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb","root","Sql@2003");
               String Id=manId_txt.getText();
               String Query="DELETE FROM MANUFACTURER WHERE MANUFACTURE_ID="+Id;
               Statement Add=Con.createStatement();
               Add.executeUpdate(Query);
               SelectMan();
                JOptionPane.showMessageDialog(this,"Company Deleted Successfully");
            }catch(SQLException e){
               e.printStackTrace();
            }
        }
    }//GEN-LAST:event_dltManBtn2ActionPerformed
public void SelectMan(){
    try{
    Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb","root","Sql@2003");
    St=Con.createStatement();
    Rs=St.executeQuery("SELECT * FROM pharmacydb.MANUFACTURER");
    ManTable.setModel(DbUtils.resultSetToTableModel(Rs));
    }catch(SQLException e){
        e.printStackTrace();
    }
}
    private void addManBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addManBtnMouseClicked
        try{
           Con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb","root","Sql@2003");
           PreparedStatement add=Con.prepareStatement("INSERT INTO MANUFACTURER VALUES(?,?)");
           add.setString(1,manId_txt.getText());
           add.setString(2,manName_txt.getText());
           int row=add.executeUpdate();
           javax.swing.JOptionPane.showMessageDialog(this,"Company added Successfully");
           Con.close();
           
           //Refresh the table after adding a new entry
           
           SelectMan();
            
        }catch(SQLException e){
             e.printStackTrace();
        }
        
    }//GEN-LAST:event_addManBtnMouseClicked

    private void dltManBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dltManBtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dltManBtn2MouseClicked

    private void ManageMed_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageMed_CloseActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            Dashboard prevPage = new Dashboard();
            prevPage.setVisible(true);
        }
    }//GEN-LAST:event_ManageMed_CloseActionPerformed

    private void ManTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManTableMouseClicked
       DefaultTableModel model=(DefaultTableModel)ManTable.getModel();
       int rowIndex=ManTable.getSelectedRow();
       if(rowIndex!=-1){
        manId_txt.setText(model.getValueAt(rowIndex,0).toString());
        manName_txt.setText(model.getValueAt(rowIndex,1).toString());
        manId_txt.setEditable(false);
       }
    }//GEN-LAST:event_ManTableMouseClicked

    private void updateManBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateManBtn1MouseClicked
        if(manId_txt.getText().isEmpty() || manName_txt.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Please fill in all required fields.");
        }
        else{
           try{
             Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacydb","root","Sql@2003");  
             String UpdateQuery="UPDATE MANUFACTURER SET M_NAME='"+manName_txt.getText()+"' WHERE MANUFACTURE_ID="+manId_txt.getText();
             Statement stmt=Con.createStatement();
             stmt.executeUpdate(UpdateQuery);
             JOptionPane.showMessageDialog(this,"Company Updated Successfully");
              SelectMan();
           }catch(SQLException e){
              e.printStackTrace();
           }
          
        }
    }//GEN-LAST:event_updateManBtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ManTable;
    private javax.swing.JButton ManageMed_Close;
    private javax.swing.JButton addManBtn;
    private javax.swing.JButton dltManBtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField manId_txt;
    private javax.swing.JTextField manName_txt;
    private javax.swing.JButton updateManBtn1;
    // End of variables declaration//GEN-END:variables
}
